displayName=Bank No Touch
author=thefriendlyhedgehog
description=Tracks bank withdrawals and shows how much GP you could earn by selling rarely-used items
tags=bank,usage,inventory,tracking,gp,sell,value,money
plugins=com.thefriendlyhedgehog.banknotouch.BankNoTouchPlugin
